### PR TITLE
Explicit HTTPS calls

### PR DESCRIPTION
**Pull request by alanyee**
Following recent guidelines to make explicit HTTPS calls

### CODE REVIEW

**Comment by alanyee** [comment]
I just signed the CLA.

**Comment by AurelioDeRosa** [comment]
Hi @alanyee. Can you please rebase your PR so that we can merge it?

**Comment by alanyee** [comment]
In what way do you want me to rebase it?

**Comment by AurelioDeRosa** [comment]
I meant using [git rebase](https://git-scm.com/docs/git-rebase).

**Comment by mgol** [comment]
@alanyee Do you need some further help?

**Comment by alanyee** [comment]
@mgol Perhaps, I am not how to use git rebase.

**Comment by mgol** [comment]
@alanyee I rebased and landed it for you. For the sake of the future you may read [our "Commits and Pull Requests" guide](https://contribute.jquery.org/commits-and-pull-requests/) and the ["Rewriting History" Atlassian tutorial](https://www.atlassian.com/git/tutorials/rewriting-history) to learn about the subject.

Thanks!

**Pull request closed without merging**
