### PR TITLE
Add section about installation using Yarn

### PR DESCRIPTION
**Pull request by julmot**
Btw: Is there a reason why some links are written in HTML and others in Markdown?

### CODE REVIEW

**Comment by dmethvin** [comment]
> Btw: Is there a reason why some links are written in HTML and others in Markdown?

The links for the files have the `download` attribute to hint the browser that they should be saved rather than displayed. We got a lot of questions about why the code was displaying and how to save it.  😸

**Comment by dmethvin** [comment]
Would it make sense to combine the Yarn and npm sections? The actual files are coming from the same place and this might make people think they're not.

**Comment by julmot** [comment]
@dmethvin Agreed, I've just merged these two sections.

**Comment by mgol** [comment]
I don't think we should mention Yarn, it's too early for that. There are a lot of alternative clients of the npm registry (e.g. [ied](https://github.com/alexanderGugel/ied)), [pnpm](https://github.com/rstacruz/pnpm) and we have to consider that every extra piece of information added to the page makes it harder for people to find information they're looking for. So far Yarn is something new & experimental; people installing it are people liking experiments and most likely familiar with how it works and that it uses the npm registry so all the packages are there.

If it turns out that in a year or two it gets quite popular & widely used then sure, let's mention it, but we shouldn't rush into anything.

**Comment by julmot** [comment]
@mgol I respect your personal opinion, but I have a different. Yarn earned over 15,000 stars in just 4 months, the ones you named have not even 2,000 (and ied exists for a long time). pnpm is not a full client, since it just replaces `npm install`. Also big companies like Facebook are already using Yarn. Last but not least Yarn will probably be named in future developer tutorials and therefore should be mentioned on jquery.com too.

**Comment by kswedberg** [comment]
@julmot what is the likelihood that a developer who is using `yarn` at this point doesn't already know that `npm install` can be swapped out for `yarn add` for any npm package? I understand that yarn is suddenly very popular, but I think we're getting ahead of ourselves if we feel the need to include instructions for it everywhere we refer to `npm`. 

My guess is that people who are using yarn at this point already know how to use it, and those who aren't using it don't need us to offer yet another way to download jQuery. Seems adding yarn instructions wouldn't do much more than signal to those "in the know" that we're hip to the new technology.

p.s. I'm using yarn and so far I really enjoy it (despite having to deal with some bugs, which is to be expected at this stage of a project's development).

**Comment by gnarf** [comment]
> people installing it are people liking experiments and most likely familiar with how it works and that it uses the npm registry so all the packages are there.

It does seem a bit redundant to specify `yarn add jquery` at this point. Yarn users know that they can just `yarn add` instead of `npm add`.

I'm not opposed to adding a callout to yarnpkg.com as an alternate package manager, I just think this takes up a lot of space with it's own code block.

**Comment by julmot** [comment]
@kswedberg 

> Seems adding yarn instructions wouldn't do much more than signal to those "in the know" that we're hip to the new technology.

I partially agree with you here. If you're going to merge this, Yarn would get a positive reputation and it would point out that there's an alternative for those who don't know it yet. So the question is, do you find it a great alternative? If so, mentioning could also make others happy. You decide, I'm out. :octocat:

**Comment by mgol** [comment]
> I'm not opposed to adding a callout to yarnpkg.com as an alternate package manager, I just think this takes up a lot of space with it's own code block.

If it's just one sentence (something like "You can also try yarn" with a link to https://yarnpkg.com/) then I agree it doesn't introduce a lot of noise and I'd be open to considering that.

And for the record, I agree with @kswedberg in that I like yarn and I experiment with it at home and one of the stars @julmot mentioned is from me. :)

**Comment by kswedberg** [comment]
@julmot whether or not they merge your PR, your contribution is appreciated. Thanks a lot for caring enough about the project to submit the pull request!

**Comment by dmethvin** [comment]
Yarn seems to be well enough established that we could land this perhaps? The only change I'd like to see is to add "or Yarn" to the section heading.

**Comment by mgol** [comment]
@dmethvin Yarn requires a different command so if we just add "or Yarn" which is then followed by an `npm install jquery` command, it will be confusing. I'd add sth like:

> or Yarn:
> `yarn add jquery`

It looks short enough.

**Comment by dmethvin** [comment]
I meant `s/ ## Downloading jQuery using npm/ ## Downloading jQuery using npm or Yarn/`

**Comment by mgol** [comment]
Yes but with the added code block for `yarn add jquery`, right?

**Comment by dmethvin** [comment]
Yep, the current PR changes with the updated headline. The second commit got rid of the duplication so it's basically just the command now.

**Comment by mgol** [comment]
Ah, you were commenting wrt the existing PR state. I agree then, it's good with the header change. 👍

**Comment by mgol** [comment]
@julmot could you sign our new CLA?

**Comment by julmot** [comment]
There you go

**Comment by mgol** [comment]
Thanks! If you update the header as @dmethvin it's good to land.

**Comment by julmot** [comment]
@mgol Sorry, but you'll have to merge it and do the changes afterwards. I've dropped the fork a long time ago.

**Comment by mgol** [comment]
@julmot No problem, I've modified the header myself and landed the PR. Thanks and sorry it took so long!

**Pull request closed without merging**
