### PR TITLE
issue#19 fix

### PR DESCRIPTION
**Pull request by ashg1910**
CLA signed

### CODE REVIEW

**Comment by arthurvr** [comment]
@ashg1910 This is your 4th PR for the same issue. Could you please just update your PR next time? Having multiple PRs for the same thing does not make sense and just makes things difficult and noisy.

**Comment by ashg1910** [comment]
@arthurvr I needed to send the PR again in order to make it CLA signed.

**Comment by arthurvr** [comment]
> I needed to send the PR again in order to make it CLA signed.

As you can read on the page [we linked to](https://github.com/jquery/jquery-wp-content/pull/354#issuecomment-89661488) you can just update your PR.

**Comment by arthurvr** [comment]
As @rxaviers [wrote in one of your earlier PRs](https://github.com/jquery/jquery.com/pull/94#discussion_r27770524), I don't think a `<div>` surrounded by an `<a>` is a good idea.

**Comment by ashg1910** [comment]
@arthurvr I guess its okay for html5 - http://stackoverflow.com/questions/1827965/is-putting-a-div-inside-an-anchor-ever-correct
will try another fix if this isn't right

**Comment by mzgol** [comment]
IMO it looks good since HTML 5 allows it. Any objections to just land it? @arthurvr, @jzaefferer?

**Comment by kswedberg** [comment]
It's fine according to HTML5 spec, but there should probably be something in the stylesheet along the lines of:

```css
.project-tiles a {
  display: block;
}
```

**Comment by mgol** [comment]
@ashg1910 I've tested it but it doesn't look like the original. The logos are aligned incorrectly etc. Have you tested it locally? If so, can you make the changes that will preserve the current layout? If not, please also write that so that we know.

We'll also need you to sign our new JS Foundation CLA, the old jQuery Foundation one no longer applies.

**Comment by mgol** [comment]
@ashg1910 Sorry, I've seen https://github.com/jquery/jquery-wp-content/pull/356 only now. Can you sign the CLA and rebase both PRs? I'd land them then.

**Comment by mgol** [comment]
@ashg1910 ping?

**Comment by mgol** [comment]
Per lack of response I'm closing this in favor of https://github.com/jquery/jquery-wp-content/pull/413 & https://github.com/jquery/jquery.com/pull/177.

**Pull request closed without merging**
