### PR TITLE
#19 javascript fix

### PR DESCRIPTION
**Pull request by ashg1910**

### CODE REVIEW

**Comment by scottgonzalez** [comment]
This not only breaks separation of concerns, but it breaks semantics and accessibility.

**Comment by ashg1910** [comment]
@scottgonzalez can you explain the flaws in this?

**Comment by scottgonzalez** [comment]
I'm sorry, but that level of assistance needs to be acquired outside of pull requests. Perhaps start with http://learn.jquery.com/ and other general resources.

**Comment by ashg1910** [comment]
Thanks :)

**Pull request closed without merging**
