### PR TITLE
[Merged] Browser support: Add Yandex.Browser to the list

### PR DESCRIPTION
**Pull request by markelog**

### CODE REVIEW

**Comment by mzgol** [comment]
This was fixed in 2260fc5f20c5d6317907d5a7ff13827393b3930a, although the commit will be rebased on top of `master` until jQuery 3.0.0 is released. @markelog did you want to wait until that happens?

@arthurvr what's the strategy you use for other content sites, like https://github.com/jquery/api.jquery.com/?

**Comment by markelog** [comment]
> This was fixed in 2260fc5, although the commit will be rebased on top of master until jQuery 3.0.0 is released. 

Yeah, exactly, commit hashes are not the same, because i added `Closes ...` comment, but they are the same, this pull will autoclose when that commit will be merged to master.

**Comment by arthurvr** [comment]
> @arthurvr what's the strategy you use for other content sites, like https://github.com/jquery/api.jquery.com/?

We just close the PRs when we land them to the v3 branch, if that's where you're asking for.

**Comment by mzgol** [comment]
When I merge a PR to the `jquery-3` branch it gets auto-closed anyway, see e.g. #107. If we didn't want to get them closed, we'd have to be sure to *always* cherry-pick, even if a commit can be merged because it's already rebased.

Losing reference to the final version of the commit is not very nice, though. :/

**Pull request closed without merging**
