### PR TITLE
Browser support: Update the site for jQuery 3.0.0

### PR DESCRIPTION
**Pull request by mzgol**
NOTE: don't merge it before we cut stable jQuery 3.0.0!

This PR is a preparation for the browser-support site changes that are needed for jQuery 3.0.0.

Apart from updating browsers' versions, I made a couple of changes:

1. I grouped Chrome, Firefox & Opera into one column; with the addition of Edge the table got *really* cramped and it may still get more entries if we decide to officially test on a Windows Phone.
2. I moved `jQuery` to be first & `jQuery Compat` to be second. At this point where we're starting discussing dropping IE8 in some not-so-absurdly-distant future, with additional platform support like Node (it wasn't really properly tested in 2.x) and, last but not least, considering that the name `jQuery` hints it is the main line it made sense to me to change the "default" version to choose.
3. Some people (hopefully not a lot) will still need to support mammoths like IE6 so I added a paragraph directing to the last version that supports them.
4. I changed `(Current - 1) or Current` to `(Current - 1) and Current` as we support both versions, not one of the other.

Edge is presented separately as we don't know if BrowserStack will make more than one build available. Edge will not have official version numbers but its user agent contains the build number in the form of `Edge/12.BUILD_NUMBER`; current build is 9600. If more than one build will be made available, I'd merge this column with the Chrome one.

Screenshots:

1. current page: screen shot 2015-06-29 at 19 20 34
2. page with this PR applied: screen shot 2015-06-29 at 19 28 55

cc @jquery/core

___

Things to consider:
* [ ] remove the "CSS contents and browser compatibility" link from "External References" at the bottom of the page; it was mostly relevant for IE<8 and most of the table has since been moved to another place.

### CODE REVIEW

**Comment by mzgol** [comment]
@markelog wanted to add the Yandex Browser as well since it's another Chromium-based browser that's quite popular in certain countries and has miniscule market share globally, just like Opera - now that we dropped Opera 12.1x, the latest non-Chromium-based one.

**Comment by scottgonzalez** [comment]
> NOTE: don't merge it before we cut stable jQuery 3.0.0!

You might consider the approach already used for other sites where a 3-0 branch would be created so that changes like this can land as they're ready. This branch would then be constantly rebased and when 3.0.0 is released, you can merge it into master as a fast forward, then delete the branch.

**Comment by mzgol** [comment]
This repo is pretty small & doesn't change a lot but if we had other changes prepared for 3.0.0 then that might be a good idea.

**Comment by gnarf** [comment]
You might consider just pushing this jquery-3 branch to the jquery repo and using it as a base for a new PR to keep the "tracking" going - other PR's can be landed against it if we have other updates.

**Comment by mzgol** [comment]
> You might consider just pushing this jquery-3 branch to the jquery repo and using it as a base for a new PR to keep the "tracking" going

OK, migrated to #103.

**Pull request closed without merging**
